# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20171214_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='course_nums',
            field=models.IntegerField(default=0, verbose_name='课程数'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='students',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=None, upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
